### ISSUE TITLE
AttributeError: Only OpenSCENARIO 1.0 is supported

### ISSUE THREAD

**Issue by vimal4353** [asam-oss/OSC-ALKS-scenarios#54] opened 2022-05-19 11:56 UTC
Hi, I tried with my own custom .xosc file. My  xosc file is created in openscenario 1.1 standard. I run the file in OSC-ALKS 0.4 release the attribute error is shown. please let me know how to solve this issue.

**Comment by arauschert** [comment] 2022-05-19 12:50
Hi! The problem is reported by the environment simulator you are using for executing the scenario. Which environment simulator are you using (CARLA, esmini...)? The problem can be fixed by either modelling the scenario with the 1.0 standard version or using a different simulator (version). Or the simulator needs to be upgraded to support also the OpenSCENARIO 1.1 standard.

**Comment by vimal4353** [comment] 2022-05-19 13:01
Thanks for the reply. I am checking in carla 0.9.11 version. I can't able to modelling the scenario with the 1.0 standard.
Could you tell me the which carla simulator version will solve this issue.

**Comment by arauschert** [comment] 2022-05-19 13:23
I think there is no Carla version yet (or more precisely carla scenario-runner) which supports OpenSCENARIO 1.1 format.

**Comment by vimal4353** [comment] 2022-05-19 13:25
> I think there is no Carla version yet (or more precisely carla scenario-runner) which supports OpenSCENARIO 1.1 format.

Thank you very much for your advice.

**Closed** 2024-07-24 11:47 UTC
